# Generated by Django 4.0 on 2025-06-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='masterdata.department')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='incidents.incident')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentquestion')),
            ],
        ),
    ]
