# Generated by Django 4.2 on 2025-07-01 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0004_incidentseverity_incidentstatus'),
        ('incidents', '0002_incident_is_deleted_incidentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_under_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IncidentTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approved_by', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_dept', to='masterdata.department')),
                ('from_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_division', to='masterdata.division')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_dept', to='masterdata.department')),
                ('to_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_division', to='masterdata.division')),
            ],
        ),
    ]
