# Generated by Django 4.0 on 2025-06-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('incidents', '0002_incidentquestion_incidentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentquestion',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='masterdata.division'),
        ),
    ]
