# Generated by Django 4.2 on 2025-07-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_is_under_transfer_incidenttransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='needs_admin_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
