# Generated by Django 4.0 on 2025-07-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('incidents', '0003_alter_incidentquestion_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentquestion',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='masterdata.department'),
        ),
    ]
