# Generated by Django 4.2 on 2025-06-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_department_division'),
        ('accounts', '0002_alter_customuserprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('function_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Audit_Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='departmentprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.department'),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.division'),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.role'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentprofile',
            unique_together={('user', 'division', 'department', 'role')},
        ),
    ]
