# Generated by Django 4.2 on 2025-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_departmentprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='unique_user_role_when_no_div_dept',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='unique_user_division_role',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='unique_user_department_role',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='unique_user_full_combo',
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('division__isnull', True)), fields=('user', 'role'), name='user already exist with same role and null division, department'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'division', 'role'), name='Unique User-division-role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True)), fields=('user', 'department', 'role'), name='Unique User-department-role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'division', 'department', 'role'), name='Already exist'),
        ),
    ]
