<<<<<<< HEAD
# Generated by Django 4.0 on 2025-06-23 07:35

=======
# Generated by Django 4.2 on 2025-06-23 08:08

from django.conf import settings
>>>>>>> 9dc7be7f515fc9630d9d35f61a9e2490dfa1a6f2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('incidents', '0001_initial'),
        ('accounts', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0002_incident_is_deleted_incidentattachment'),
>>>>>>> 9dc7be7f515fc9630d9d35f61a9e2490dfa1a6f2
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
<<<<<<< HEAD
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='incidents.incident')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuserprofile')),
=======
                ('is_internal_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='incidents.incident')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
>>>>>>> 9dc7be7f515fc9630d9d35f61a9e2490dfa1a6f2
            ],
        ),
        migrations.CreateModel(
            name='IncidentMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('file', models.FileField(upload_to='incident_message_attachments/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communication.incidentmessage')),
=======
                ('file', models.FileField(upload_to='message_attachments/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgAttachments', to='communication.incidentmessage')),
>>>>>>> 9dc7be7f515fc9630d9d35f61a9e2490dfa1a6f2
            ],
        ),
    ]
