# Generated by Django 4.2 on 2025-06-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_department_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='division',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
