# Generated by Django 4.2.5 on 2025-06-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuserprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
