# Generated by Django 4.2 on 2025-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog_alter_departmentprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('division__isnull', True)), fields=('user', 'role'), name='unique_user_role_when_no_div_dept'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'division', 'role'), name='unique_user_division_role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True)), fields=('user', 'department', 'role'), name='unique_user_department_role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'division', 'department', 'role'), name='unique_user_full_combo'),
        ),
    ]
