# Generated by Django 4.2 on 2025-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_incidentseverity_incidentstatus'),
        ('accounts', '0007_menu_rolemenumapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.incidentstatus')),
            ],
            options={
                'unique_together': {('role', 'status')},
            },
        ),
    ]
