# Generated by Django 4.2 on 2025-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rolestatusmapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='user already exist with same role and null division, department',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='Unique User-division-role',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='Unique User-department-role',
        ),
        migrations.RemoveConstraint(
            model_name='departmentprofile',
            name='Already exist',
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('division__isnull', True), ('is_deleted', False)), fields=('user', 'role'), name='user already exist with same role and null division, department'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('is_deleted', False)), fields=('user', 'division', 'role'), name='Unique User-division-role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True), ('is_deleted', False)), fields=('user', 'department', 'role'), name='Unique User-department-role'),
        ),
        migrations.AddConstraint(
            model_name='departmentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'division', 'department', 'role'), name='Already exist'),
        ),
    ]
