# Generated by Django 4.0 on 2025-06-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.incidentstatus')),
            ],
            options={
                'unique_together': {('role', 'status')},
            },
        ),
    ]
